/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_appsync_graphqlEndpoint:
    "https://mu5td26ayvbjrovpf6pm6brf34.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-northeast-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-jq4f3a74zjfutpztklmda4bcxm",
  aws_cognito_identity_pool_id:
    "ap-northeast-1:669ca797-38d0-44a9-87c1-ff4274cb6f79",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_2TAYsOdG1",
  aws_user_pools_web_client_id: "5ibdgn3ilfmd5vqkcfrgc3t976",
  oauth: {},
};

export default awsmobile;
